Network:
  epochs: 2
  batch_size: 5
  n_steps: 5
  dataset: "Nordland"
  rule: "TSSLBP"
  data_path: "datasets/nordland"
  lr: 0.0005
  loss: "kernel"
  n_class: 100
  desired_count: 4
  undesired_count: 1
  tau_m: 5
  tau_s: 3
  model: "LIF"

Layers:
  conv_1:
    type: "conv"
    in_channels: 1
    out_channels: 15
    kernel_size: 5
    weight_scale: 1
    padding: 0
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2
    threshold: 1

  conv_2:
    type: "conv"
    in_channels: 15
    out_channels: 40
    kernel_size: 5
    weight_scale: 1
    padding: 0
    threshold: 1

  pooling_2:
    type: "pooling"
    kernel_size: 2
    threshold: 1

  FC_1:
    type: "linear"
    n_inputs: 640
    n_outputs: 300
    weight_scale: 1
    threshold: 1

  output:
    type: "linear"
    n_inputs: 300
    n_outputs: 100
    weight_scale: 1
    threshold: 1
